x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  APP_ENV: prod
  DB_NAME: database.sqlite
  REDIS_URL: redis://redis:6379
  REDIS_HOST: redis
  REDIS_PORT: 6379
  PASSWORD: 99e869389982e8169a65bc60c3cb07b9fa0f9d22ae4e58b15428eaea91895977
  
services:
  app:
    image: mdlab_server:latest
    container_name: mdlab_server
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    depends_on:
      - redis
    volumes:
      - ./storage/sqlite:/data:rw
    networks:
      - app-network
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
